//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "terms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_terms_group_version")]
    pub group: String,
    pub url: String,
    #[sea_orm(unique_key = "idx_terms_group_version")]
    pub version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub info: Option<String>,
    pub created_at: DateTime,
    #[sea_orm(has_many)]
    pub user_agreements: HasMany<super::user_agreements::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
