//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_agreements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub term_of_use_id: i32,
    pub user_id: i32,
    pub agreed_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "term_of_use_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub terms: HasOne<super::terms::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
